name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  main:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x, 15.x]

    env:
      ELM_HOME: '${{ github.workspace }}/elm-stuff/elm-home'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Cache ELM_HOME
        uses: actions/cache@v2
        with:
          path: '${{ env.ELM_HOME }}'
          key: elm-${{ matrix.os }}-${{ hashFiles('elm-tooling.json', 'elm/**/elm.json', 'example-*/**/elm.json', 'tests/**/elm.json') }}

      - name: npm ci
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NO_ELM_TOOLING_INSTALL: 1

      - name: elm-tooling install
        run: npx --no-install elm-tooling install

      - name: Mocha
        run: npx --no-install mocha tests

      - name: elm-test
        run: npm run elm-test


  publish:
    needs: main
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        env:
          INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          TAG="latest-$(npx semver -c ${{ steps.publish.outputs.version }})"
          npm dist-tag add elm-test@${{ steps.publish.outputs.version }} $TAG

      - name: Create Release
        if: steps.publish.outputs.type != 'none'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          release_name: Release ${{ steps.publish.outputs.version }}
          body: ""
          draft: false
          prerelease: false
